language: node_js
node_js:
  - "8"
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-durandal' ]; then cd .. && eval "mv $currentfolder generator-durandal" && cd generator-durandal; fi

